# Prototype: reproduces bundle/datasources/prometheus-prod.md as if generated by an
# "okf-datasource" module call next to wherever Prometheus itself is provisioned.
#
# Writes into ./output/ (gitignored), NOT into the real bundle/.

module "prometheus_datasource" {
  source = "../../modules/okf-datasource"

  bundle_root = "${path.module}/output"
  id          = "prometheus-prod"

  title       = "Prometheus (prod)"
  description = "Primary Prometheus instance scraping the checkout stack."
  resource    = "https://prometheus.prod.internal.example.com"

  owner = "observability-team"
  tags  = ["prometheus"]

  freetext = <<-EOT
    Backs every [metric](../metrics/) referenced by the [checkout journey](../journeys/checkout.md)'s
    SLIs.
  EOT
}

output "datasource_id" {
  value = module.prometheus_datasource.id
}

output "datasource_filename" {
  value = module.prometheus_datasource.filename
}
