# Prototype: what it would look like if bundle/subsystems/{cart,payment}-service.md were
# generated by "okf-subsystem" module calls sitting next to the resources that define
# those services, instead of hand-authored in the bundle repo.
#
# Also demonstrates cross-module linking via the md_link output: two Subsystems that
# reference each other in prose, same as the real hand-authored files do. This works in
# *both* directions with no dependency cycle, because md_link/concept_id/relative_path
# are pure functions of a module's own title/id input variables — never derived from any
# resource inside the module — so neither module's output actually depends on the
# other module's resources being created first. Verified: a mutual reference in both
# directions applies cleanly and produces a byte-correct, idempotent result.
#
# Writes into ./output/ (gitignored), NOT into the real bundle/ — this is a
# side-by-side prototype, not a replacement of the pilot bundle yet.

module "payment_service_subsystem" {
  source = "../../modules/okf-subsystem"

  bundle_root = "${path.module}/output"
  id          = "payment-service"

  title       = "Payment Service"
  description = "Charges the customer's payment method and returns success/failure to checkout-api."
  resource    = "git@example.com:acme/payment-service.git"

  owner    = "payments-team"
  tags     = ["checkout", "payments"]
  journeys = ["journeys/checkout"]

  # payment-service.md lives in the same directory (subsystems/) as cart-service.md, so
  # the "../subsystems/" prefix md_link assumes must be stripped for a same-directory link.
  freetext = <<-EOT
    Sits between ${replace(module.cart_service_subsystem.md_link, "../subsystems/", "")} and [checkout-api](checkout-api.md) in the
    [checkout journey](../journeys/checkout.md). Its latency directly backs the
    [payment latency SLO](../slos/payment-latency-slo.md) — this is the subsystem to look at first
    when that SLO is breaching.
  EOT
}

module "cart_service_subsystem" {
  source = "../../modules/okf-subsystem"

  bundle_root = "${path.module}/output"
  id          = "cart-service"

  title       = "Cart Service"
  description = "Stores and mutates the customer's shopping cart before checkout begins."
  resource    = "git@example.com:acme/cart-service.git"

  owner    = "checkout-team"
  tags     = ["checkout"]
  journeys = ["journeys/checkout"]

  freetext = <<-EOT
    Owns cart state until checkout hands off to ${replace(module.payment_service_subsystem.md_link, "../subsystems/", "")}. Part of the
    [checkout journey](../journeys/checkout.md).
  EOT
}

output "subsystem_id" {
  value = module.cart_service_subsystem.id
}

output "subsystem_filename" {
  value = module.cart_service_subsystem.filename
}

output "payment_subsystem_md_link" {
  value = module.payment_service_subsystem.md_link
}
