# Prototype: what it would look like if bundle/services/{cart,payment}-service.md were
# generated by "okf-service" module calls sitting next to the resources that define
# those services, instead of hand-authored in the bundle repo.
#
# Replaces the retired ../cart-service/ example, which called okf-subsystem for these two
# concepts back when VOCABULARY.md's pre-v0.2.0 vocabulary modeled them as Subsystems (see
# bundle/log.md's v0.2.0 migration entry) -- same bidirectional-cross-link demonstration,
# now via okf-service. cart-service also wires its `subsystems` back-ref to the real
# bundle/subsystems/cart-service-redis.md (see ../cart-service-redis/), as a literal concept
# ID rather than a cross-example module reference -- each example here is an independent
# root module, same convention as every other pair in ../.
#
# Writes into ./output/ (gitignored), NOT into the real bundle/ -- this is a
# side-by-side prototype, not a replacement of the migrated bundle.

module "payment_service" {
  source = "../../modules/okf-service"

  bundle_root = "${path.module}/output"
  id          = "payment-service"

  title       = "Payment Service"
  description = "Charges the customer's payment method and returns success/failure to checkout-api."
  resource    = "git@example.com:acme/payment-service.git"

  owner    = "payments-team"
  tags     = ["checkout", "payments"]
  journeys = ["journeys/checkout"]

  # payment-service.md lives in the same directory (services/) as cart-service.md, so
  # the "../services/" prefix md_link assumes must be stripped for a same-directory link.
  freetext = <<-EOT
    Sits between ${replace(module.cart_service.md_link, "../services/", "")} and [checkout-api](checkout-api.md) in the
    [checkout journey](../journeys/checkout.md). Its latency directly backs the
    [payment latency SLO](../slos/payment-latency-slo.md) — this is the service to look at first
    when that SLO is breaching.
  EOT
}

module "cart_service" {
  source = "../../modules/okf-service"

  bundle_root = "${path.module}/output"
  id          = "cart-service"

  title       = "Cart Service"
  description = "Stores and mutates the customer's shopping cart before checkout begins."
  resource    = "git@example.com:acme/cart-service.git"

  owner      = "checkout-team"
  tags       = ["checkout"]
  journeys   = ["journeys/checkout"]
  subsystems = ["subsystems/cart-service-redis"]

  freetext = <<-EOT
    Owns cart state until checkout hands off to ${replace(module.payment_service.md_link, "../services/", "")}. Part of the
    [checkout journey](../journeys/checkout.md).
  EOT
}

output "service_id" {
  value = module.cart_service.id
}

output "service_filename" {
  value = module.cart_service.filename
}

output "payment_service_md_link" {
  value = module.payment_service.md_link
}
